version: '3'
services:

  fiber-billing-db:
    image: "postgres:14.4-alpine"
    container_name: "fiber-billing-db"
    healthcheck:
      test: ["CMD", "pg_isready", "-q", "-d", "postgres", "-U", "root" ]
      interval: 10s
      timeout: 40s
      retries: 10
    volumes:
      - fiber-billing-data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    ports:
      - 5432:5432
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
      - APP_DB_NAME=fiber-billing
      - APP_DB_USER=fiber-billing
      - APP_DB_PASSWORD=fiber-billing
      - POSTGRES_USER=root
      - POSTGRES_PASSWORD=password

  fiber-billing-backend:
    build: ./backend
    container_name: fiber-billing-backend
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fiber-billing-db:5432/fiber-billing
      - SPRING_DATASOURCE_USERNAME=fiber-billing
      - SPRING_DATASOURCE_PASSWORD=fiber-billing
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8080:8080
    depends_on:
      - fiber-billing-db 

  fiber-billing-frontend:
    build: ./frontend
    container_name: fiber-billing-frontend
    ports:
      - 4200:80
    depends_on:
      - fiber-billing-backend

volumes:
  fiber-billing-data:
