version: "3"
services:

  fiber-billing-db:
    image: "postgres:14.4-alpine"
    restart: unless-stopped
    volumes:
      - data:/var/lib/postgresql/data
      - ./db:/docker-entrypoint-initdb.d/
    environment:
      POSTGRES_DB: ${POSTGRESQL_DB}
      POSTGRES_USER: ${POSTGRESQL_USER}
      POSTGRES_PASSWORD: ${POSTGRESQL_PASS}
      APP_DB_USER: ${APP_DB_USER}
      APP_DB_NAME: ${APP_DB_NAME}
      APP_DB_PASS: ${APP_DB_PASS}
    ports:
      - 5432:5432
    
  fiber-billing-keycloak:
    image: "jboss/keycloak:16.1.1"
    restart: unless-stopped
    environment:
      DB_VENDOR: POSTGRES
      DB_ADDR: fiber-billing-db
      DB_DATABASE: ${POSTGRESQL_DB}
      DB_USER: ${POSTGRESQL_USER}
      DB_PASSWORD: ${POSTGRESQL_PASS}
      KEYCLOAK_USER: ${KEYCLOAK_USER}
      KEYCLOAK_PASSWORD: ${KEYCLOAK_PASSWORD}
    ports:
      - 8080:8080
    depends_on:
      - fiber-billing-db

  fiber-billing-backend:
    build: ./backend
    restart: unless-stopped
    environment:
      - SPRING_DATASOURCE_URL=jdbc:postgresql://fiber-billing-db:5432/fiber-billing
      - SPRING_DATASOURCE_USERNAME=fiber-billing
      - SPRING_DATASOURCE_PASSWORD=fiber-billing
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    ports:
      - 8000:8000
    depends_on:
      - fiber-billing-db

  fiber-billing-frontend:
    build: ./frontend
    ports:
      - 4200:80
    depends_on:
      - fiber-billing-backend

volumes:
  data:
    driver: local
