stages:
  - build
  - test

build-job:
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar

test-job:
  stage: test
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar
