variables:
  MAVEN_OPTS: "-Djava.awt.headless=true -Dmaven.repo.local=./.m2/repository"
  MAVEN_CLI_OPTS: "--batch-mode --errors --fail-at-end --show-version"

cache:
  paths:
    - ./.m2/repository
  # keep cache across branch
  key: "$CI_BUILD_REF_NAME"

stages:
  - build
  - test

build-job:
  image: maven:3.8.3-openjdk-17
  stage: build
  script: 
    - "mvn clean compile $MAVEN_CLI_OPTS"
  artifacts:
    paths:
      - target/*.jar

test-job:
  image: maven:3.8.3-openjdk-17
  stage: test
  script: 
    - "mvn package $MAVEN_CLI_OPTS"
  artifacts:
    paths:
      - target/*.jar
