cache:
  paths:
    - .m2/repository

varaibles:
  MAVEN_OPTS: "-Dmaven.repo.local=$CI_PROJECT_DIR/.m2/repository"


stages:
  - build
  - test

build-job:
  image: maven:3.8.3-openjdk-17
  stage: build
  script: "mvn clean package -B"
  artifacts:
    paths:
      - target/*.jar

test-job:
  image: maven:3.8.3-openjdk-17
  stage: test
  script: "mvn test"
  artifacts:
    paths:
      - target/*.jar
