stages:
  - build
  - test

build-job:
  image: maven:3.8.3-openjdk-17
  stage: build
  script: 
    - "mvn -f backend package -B"
  artifacts:
    paths:
      - backend/target/*.jar

test-job:
  image: maven:3.8.3-openjdk-17
  stage: test
  script: 
    - "mvn -f backend test"
  artifacts:
    paths:
      - backend/target/*.jar
